### ISSUE TITLE
brand option in android was unclickable, not going brand page

### ISSUE THREAD

**Issue by Animoki** [ZateLabClients/animok-issues#50] opened 2023-05-23 16:27 UTC
Uploading WhatsApp Video 2023-05-23 at 7.25.18 PM.mp4…

**Comment by Animoki** [comment] 2023-05-23 16:41
same issue in IOS also

**Comment by ZateLabClients** [comment] 2023-05-28 14:40
Duplicate of #51

**Closed by ZateLabClients** 2023-05-28 14:40 UTC
